# Generated by Django 5.2 on 2025-05-30 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
