# Generated by Django 4.2.20 on 2025-05-29 07:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
