# Generated by Django 4.2.20 on 2025-05-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('audio', 'Audio Response'), ('video', 'Video Response'), ('coding', 'Coding Question')], max_length=10)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
