# Generated by Django 4.2.20 on 2025-05-22 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_execution', '0001_initial'),
        #('test_creation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        #migrations.AddField(
            #model_name='testsession',
            #name='test',
            #field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_creation.test'),
       # ),
        migrations.AddField(
            model_name='proctoringlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_execution.testsession'),
        ),
        migrations.AddField(
            model_name='proctorcomment',
            name='proctor',
            field=models.ForeignKey(limit_choices_to={'role': 'proctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctorcomment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_execution.testsession'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_creation.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_execution.testsession'),
        ),
    ]
