# Generated by Django 4.2.20 on 2025-06-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0003_remove_sectiontimer_session_id_and_more'),
        ('test_execution', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_type',
            new_name='section_type',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='proctoringlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='proctoringscreenshot',
            name='session',
        ),
        migrations.AddField(
            model_name='answer',
            name='candidate_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_creation.candidate_test'),
        ),
        migrations.AddField(
            model_name='proctoringlog',
            name='candidate_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='test_creation.candidate_test'),
        ),
        migrations.AddField(
            model_name='proctoringscreenshot',
            name='candidate_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_screenshots', to='test_creation.candidate_test'),
        ),
    ]
