# Generated by Django 4.2.20 on 2025-05-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0005_videoresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresponse',
            name='question',
        ),
    ]
