# Generated by Django 4.2.20 on 2025-05-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0007_alter_videoresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoquestion',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
