# Generated by Django 4.2.20 on 2025-05-27 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0009_demoaudioresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_content',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='marks_awarded',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_answers/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_answers/'),
        ),
    ]
