# Generated by Django 4.2.20 on 2025-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0010_remove_answer_answer_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
