# Generated by Django 4.2.20 on 2025-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0011_alter_answer_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
