# Generated by Django 4.2.20 on 2025-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0012_answer_marked_for_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='session',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
