# Generated by Django 4.2.20 on 2025-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0014_answer_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='event_type',
            field=models.CharField(choices=[('face_not_detected', 'Face Not Detected'), ('noise', 'Noise'), ('multiple_people', 'Multiple People'), ('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit')], max_length=50),
        ),
    ]
