# Generated by Django 4.2.20 on 2025-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0015_alter_proctoringlog_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringlog',
            name='session',
        ),
        migrations.AddField(
            model_name='proctoringlog',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
