# Generated by Django 4.2.20 on 2025-05-31 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0016_remove_proctoringlog_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
