# Generated by Django 4.2.20 on 2025-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0017_alter_answer_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
