# Generated by Django 4.2.20 on 2025-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0018_alter_answer_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='section_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
