# Generated by Django 4.2.20 on 2025-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0019_answer_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='event_type',
            field=models.CharField(choices=[('face_not_detected', 'Face Not Detected'), ('noise', 'Noise'), ('multiple_people', 'Multiple People'), ('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('WindowBlur', 'Window Blur')], max_length=50),
        ),
    ]
