# Generated by Django 4.2.20 on 2025-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0020_alter_proctoringlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
