# Generated by Django 5.2.1 on 2025-06-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0021_answer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='proctoring_screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
