# Generated by Django 4.2.20 on 2025-06-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0022_proctoringscreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='marks_allotted',
            field=models.FloatField(default=0),
        ),
    ]
