<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-05 17:46
=======
# Generated by Django 5.2.1 on 2025-06-05 15:51
# Generated by Django 4.2.20 on 2025-06-05 15:55
>>>>>>> 53059defcb10635b8ea35409253e4b32548ed303

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0023_answer_evaluated_answer_marks_allotted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringscreenshot',
            name='session',
            field=models.IntegerField(),
        ),
    ]
