# Generated by Django 5.2 on 2025-06-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_execution', '0024_alter_proctoringscreenshot_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringlog',
            name='event_type',
            field=models.CharField(choices=[('face_not_detected', 'Face Not Detected'), ('noise', 'Noise'), ('multiple_people', 'Multiple People'), ('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('WindowBlur', 'Window Blur'), ('low_audio', 'Low Audio'), ('camera_off', 'Camera Off')], max_length=50),
        ),
    ]
