# Generated by Django 4.2.20 on 2025-05-22 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('subjective', 'Subjective'), ('code', 'Coding'), ('fill_in_the_blanks', 'Fill in the Blanks')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField()),
                ('marks', models.PositiveIntegerField()),
                ('negative_marks', models.FloatField(default=0.0)),
                ('time_limit_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('referenced_content_id', models.IntegerField(blank=True, null=True)),
                ('blanks', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('time_limit_sec', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_navigation', models.BooleanField(default=True)),
                ('show_question_list', models.BooleanField(default=True)),
                ('negative_marking', models.BooleanField(default=False)),
                ('navigation_type', models.CharField(choices=[('free', 'Free'), ('linear', 'Linear'), ('restricted', 'Restricted')], default='free', max_length=20)),
            ],
        ),
    ]
