# Generated by Django 5.2 on 2025-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_test',
            name='date_invited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_test',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
