# Generated by Django 5.2 on 2025-06-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_test',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='The date and time when this specific invitation expires.', null=True),
        ),
    ]
