# Generated by Django 5.2 on 2025-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.AddField(
            model_name='candidate_test',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='The date and time when this specific invitation expires.', null=True),
        ),
        migrations.AlterField(
            model_name='candidate_test',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
