# Generated by Django 5.2 on 2025-06-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0002_alter_question_correct_answer_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
