# Generated by Django 5.2 on 2025-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0002_candidate_test_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fib_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for FIB, Subjective, or joined for MCQ', null=True),
        ),
    ]
