# Generated by Django 4.2.20 on 2025-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('subjective', 'Subjective'), ('code', 'Coding'), ('fill_in_the_blank', 'Fill in the Blank'), ('audio', 'Audio'), ('video', 'Video'), ('integer', 'Integer')], max_length=50),
        ),
    ]
