# Generated by Django 4.2.20 on 2025-06-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0003_remove_sectiontimer_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiontimer',
            name='section_id',
        ),
        migrations.AddField(
            model_name='sectiontimer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_creation.section'),
        ),
    ]
