# Generated by Django 4.2.20 on 2025-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('remaining_time', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
