# Generated by Django 5.2 on 2025-06-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0003_remove_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, help_text='List of correct answers for single or multi-answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text='Used for passage sub-questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='test_creation.question'),
        ),
        migrations.AddField(
            model_name='section',
            name='max_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='min_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='negative_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='question_type',
            field=models.CharField(default='text', help_text='Only one type per section (e.g., text, mcq, fill-in-blanks, passage)', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='test_creation.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_time',
            field=models.PositiveIntegerField(default=60, help_text='Max seconds allowed for audio response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The prompt or question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple-choice', 'Multiple Choice'), ('fill-in-blanks', 'Fill in the Blanks'), ('passage', 'Passage'), ('video', 'Video Response'), ('audio', 'Audio Response')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_time',
            field=models.PositiveIntegerField(default=60, help_text='Max seconds allowed for video response'),
        ),
        migrations.AlterField(
            model_name='section',
            name='interview_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='marks_per_question',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(help_text='e.g., technical, aptitude', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True),
        ),
    ]
