# Generated by Django 5.2 on 2025-06-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0004_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='allow_navigation',
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='navigation_type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='negative_marking',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_question_list',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='total_marks',
        ),
    ]
