# Generated by Django 4.2.20 on 2025-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0004_remove_sectiontimer_section_id_sectiontimer_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_test',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
