# Generated by Django 5.2 on 2025-06-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0002_remove_test_end_date_remove_test_start_date_and_more'),
        ('test_creation', '0004_remove_sectiontimer_section_id_sectiontimer_section'),
    ]

    operations = [
    ]
