# Generated by Django 5.2 on 2025-06-20 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_creation', '0005_merge_20250620_1530'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_test',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='users.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate_test',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='test_creation.test'),
        ),
    ]
