# Generated by Django 5.2 on 2025-05-22 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_email_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
